version: '3.9'
services:
  db-service1:
    image: 'mysql:latest'
    container_name: 'db-carinventoryservice'
    environment:
      - 'MYSQL_DATABASE=db_car_repo'
      - 'MYSQL_ROOT_PASSWORD=micro1'
      - 'MYSQL_USER=micro1'
      - 'MYSQL_PASSWORD=micro1'
    ports:
      - '5400:3306'
    networks:
      - red
  app-docker:
    container_name: 'carinventoryservicecontainer-app'
    image: 'imageservice1-app:1.0.0'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8080'
    depends_on:
      - db-service1
    environment:
      - DATABASE_URL=jdbc:mysql://db-service1:3306/db_car_repo
      - DATABASE_USERNAME=micro1
      - DATABASE_PASSWORD=micro1
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://host.docker.internal:8070/eureka/
    networks:
      - red
networks:
  red:
    name: 'red'
